"""Trusted, read-only Git queries; never an arbitrary command compatibility mode."""

import os
import stat
from dataclasses import replace
from pathlib import Path

from host_support.cancellation import checkpoint
from host_support.filesystem import list_directory, open_directory, open_file, stat_at
from host_support.processes import ProcessStartError
from host_support.windows_files import validate_snapshot_names


def validate_git_query(command):
    """Defense in depth for argv generated by the built-in query tools only."""
    if not command or command[0] != "git":
        raise ValueError("Expected a trusted Git query")
    index = 1
    while index < len(command):
        if command[index] == "-c":
            index += 2
        elif command[index] in {"--no-pager", "--no-optional-locks", "--no-replace-objects"}:
            index += 1
        else:
            break
    if index >= len(command) or command[index] not in {
        "rev-parse",
        "status",
        "diff",
        "log",
        "ls-tree",
        "cat-file",
        "diff-tree",
        "config",
    }:
        raise ValueError("Windows Git compatibility only permits built-in read queries")
    if command[index] == "config" and tuple(command[index + 1 :]) != (
        "--includes",
        "--null",
        "--get-regexp",
        r"^(extensions\.partialclone|remote\..*\.promisor)$",
    ):
        raise ValueError("Windows Git compatibility does not permit configuration writes")


def copy_git_runtime(source, destination, *, limit=2 * 1024**3):
    """Copy built-in Git and its DLLs by value, including installed hard links.

    No shell, git-lfs, helper executables, hooks or templates are needed by the
    fixed query tools. Source ACLs and link identities are never copied/changed.
    Workspace and Git metadata copies keep their stricter single-link policy.
    """
    source, destination = Path(source), Path(destination)
    if source.resolve(strict=True) != source.absolute():
        raise ValueError("Git runtime cannot traverse links or reparse points")
    destination.mkdir(parents=True)
    fd = open_directory(source)
    total = 0
    try:
        for name in list_directory(fd):
            checkpoint()
            if name.lower() != "git.exe" and not name.lower().endswith(".dll"):
                continue
            validate_snapshot_names([name])
            if not stat.S_ISREG(stat_at(name, dir_fd=fd).st_mode):
                raise ValueError(f"Git runtime contains a link or special file: {name}")
            if os.name == "nt":
                from host_support.windows_files import open_trusted_runtime_file

                incoming_fd = open_trusted_runtime_file(name, dir_fd=fd)
            else:
                incoming_fd = open_file(name, dir_fd=fd)
            with os.fdopen(incoming_fd, "rb") as incoming:
                if not stat.S_ISREG(os.fstat(incoming.fileno()).st_mode):
                    raise ValueError("Git runtime source is not a regular file")
                with (destination / name).open("xb") as outgoing:
                    while chunk := incoming.read(1024 * 1024):
                        total += len(chunk)
                        if total > limit:
                            raise ValueError(
                                "Windows native Git runtime exceeds the copy size limit"
                            )
                        outgoing.write(chunk)
                        checkpoint()
    finally:
        os.close(fd)
    if not (destination / "git.exe").is_file():
        raise ValueError("Git runtime is missing git.exe")


class WindowsGitRunner:
    """Injected only into the four factory-owned Git query tools on the host."""

    def __init__(self, backend, max_output_bytes):
        self.backend = backend
        self.max_output_bytes = max_output_bytes

    def run(self, command, *, cwd, timeout_seconds):
        if not self.backend.healthy:
            raise ProcessStartError(RuntimeError("Native backend cleanup is unconfirmed"))
        try:
            return self.backend._run(
                command,
                cwd=cwd,
                timeout=timeout_seconds,
                max_output_bytes=self.max_output_bytes,
                git_read=True,
            )
        except (OSError, ValueError) as error:
            raise ProcessStartError(error) from error


class GitQueryProcess:
    """Translate only repository discovery, never arbitrary output or arguments."""

    def __init__(self, process, call, private_workspace, workspace):
        self.process = process
        self.call = call
        self.private_workspace = private_workspace
        self.workspace = workspace

    @property
    def last_cleanup_status(self):
        return self.process.last_cleanup_status

    def run(self, *, timeout_seconds):
        result = self.process.run(timeout_seconds=timeout_seconds)
        if (
            self.call.command[-2:] == ("rev-parse", "--show-toplevel")
            and result.exit_code == 0
            and not result.stdout_truncated
        ):
            relative = Path(result.stdout.rstrip("\r\n")).relative_to(self.private_workspace)
            result = replace(result, stdout=str(self.workspace / relative) + "\n")
        return result
